name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16

      - name: build it
        id: build
        shell: pwsh
        run: ./build_server.ps1

      - run: echo "$FILE_NAME"
        env:
          FILE_NAME: ${{ steps.build.outputs.ZIP_NAME }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.build.outputs.ZIP_NAME }}
          path: './Server/${{ steps.build.outputs.ZIP_NAME }}'
          if-no-files-found: error
          retention-days: 3

      
