name: Build Modules

on:
  push:
    paths:
      - '**.ps1'
      - '**.yml'
  pull_request:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        versions: [ {branch: 'master', version: '0.13.5.3.26535'}, {branch: '3.8.0', version: '0.14.1.0.28744'}]
    
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run build script
        id: build
        shell: pwsh
        run: ./build_modules.ps1 -Overwrite -Branch ${{ matrix.versions.branch }} -Url ${{ secrets.DLL_URL }} -TarkovVersion ${{ matrix.versions.version }}

      - run: echo "$FILE_NAME"
        env:
          FILE_NAME: ${{ steps.build.outputs.ZIP_NAME }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.build.outputs.ZIP_NAME }}
          path: './Modules/${{ steps.build.outputs.ZIP_NAME }}'
          if-no-files-found: error
          retention-days: 3

      
