name: Build Aki Projects

on:
  push:
    branches:
      - 'master'
    paths:
      - '**.ps1'
      - '**.yml'
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  job1:
    name: Build Aki Server SIT
    strategy:
      fail-fast: false
      matrix:
        versions:
          [{
            sbranch: "3.8.0",
            node: 20
          }]
    
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Download Aki Server package-lock.json
        shell: pwsh
        run: Invoke-WebRequest -Uri "https://dev.sp-tarkov.com/SPT-AKI/Server/raw/branch/${{ matrix.versions.sbranch }}/project/package-lock.json" -OutFile "./package-lock.json"
      
      - uses: actions/setup-node@v4
        with:
          node-version:  ${{ matrix.versions.node }}
          cache: 'npm'
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6

      - name: Build Aki Server
        id: build
        shell: pwsh
        run: ./build_server.ps1 -SIT -Release -Overwrite -NoZip -Branch ${{ matrix.versions.sbranch }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.ZIP_NAME }}
          path: './Server/project/build/*'
          if-no-files-found: error
          retention-days: 3
          compression-level: 9

  job2:
    name: Build Windows Aki Packages
    strategy:
      fail-fast: false
      matrix:
        versions:
          [{
            sbranch: "3.8.0",
            lbranch: "3.8.0",
            mbranch: "3.8.0",
            version: "0.14.1.1.28965",
            dll_url: "https://github.com/yhl452493373/SPT-AKI_DLL/raw/main/",
            node: 20
          }]
          # [
          #   {
          #     sbranch: "master",
          #     lbranch: "master",
          #     mbranch: "master",
          #     version: "0.13.5.3.26535",
          #     node: 18
          #   },
          #   {
          #     sbranch: "3.8.0",
          #     lbranch: "3.8.0",
          #     mbranch: "3.8.0",
          #     version: "0.14.1.0.28744",
          #     node: 20
          #   },
          # ]

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Aki Server package-lock.json
        shell: pwsh
        run: Invoke-WebRequest -Uri "https://dev.sp-tarkov.com/SPT-AKI/Server/raw/branch/${{ matrix.versions.sbranch }}/project/package-lock.json" -OutFile "./package-lock.json"
      
      - uses: actions/setup-node@v4
        with:
          node-version:  ${{ matrix.versions.node }}
          cache: 'npm'
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6

      - name: Build Aki Server
        id: build_server
        shell: pwsh
        run: ./build_server.ps1 -Release -Overwrite -NoZip -Branch ${{ matrix.versions.sbranch }}
   
      - name: Build Aki Modules
        id: build_modules
        shell: pwsh
        run: ./build_modules.ps1 -Overwrite -NoZip -Branch ${{ matrix.versions.mbranch }} -Url ${{ matrix.versions.dll_url }} -TarkovVersion ${{ matrix.versions.version }}

      - name: Build Aki Launcher
        id: build_launcher
        shell: pwsh
        run: ./build_launcher.ps1 -Overwrite -Branch ${{ matrix.versions.lbranch }}

      - name: Make Final Package
        id: build_packege
        shell: pwsh
        run: .\build_full_package.ps1 -Overwrite -PkgOnly

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_modules.outputs.ZIP_NAME }}
          path: './Modules/project/Build/*'
          if-no-files-found: error
          retention-days: 3
          compression-level: 9

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_server.outputs.ZIP_NAME }}
          path: './Server/project/build/*'
          if-no-files-found: error
          retention-days: 3
          compression-level: 9

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_packege.outputs.ZIP_NAME }}
          path: "./output/*"
          if-no-files-found: error
          retention-days: 3
          compression-level: 9
