name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16
          
      - name: Checkout
      - uses: actions/checkout@v3
        with:
          repository: 'https://dev.sp-tarkov.com/SPT-AKI/Server.git'
          lfs: true
          submodules: true

      - run: cd ./project

      - name: check files
        run: ls ./
      
      - run: npm ci
      - run: npm run build:debug

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: SPT-Aki
          # A file, directory or wildcard pattern that describes what to upload
          path: './build'
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
      
          retention-days: 3

      
